
# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: '3w6hs'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["beekeeb/3w6hs"]'
